AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvironmentCode:
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - stg
      - prod
      - sandbox
    Description: The environment code used in the naming of all AWS services.

Description: 'This template deploys the cloud infrastructure for the graph-ui application'

Resources:
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: "s3-${AWS::Region}-${EnvironmentCode}-graph-ui"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      VersioningConfiguration:
        Status: Enabled

  AppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: AppBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource:
              Fn::Join: [ "", [ !GetAtt AppBucket.Arn, "/*" ] ]
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: "origin access control(OAC) for allowing cloudfront to access S3 bucket"
        Name:
          Fn::Sub: "cloudfront-${AWS::Region}-${EnvironmentCode}-graph-ui-OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - AppBucket
    Properties:
      DistributionConfig:
        Comment:
          Fn::Sub: "CloudFront distribution for graph-ui"
        Origins:
          - DomainName: !GetAtt AppBucket.RegionalDomainName
            Id: static-hosting
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        Enabled: "true"
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        HttpVersion: http2
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          TargetOriginId: static-hosting
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https

Outputs:
  S3ARN:
    Value: !GetAtt AppBucket.Arn
    Description: ARN for S3 bucket
  S3Name:
    Value: !Ref AppBucket
    Description: Name of S3 bucket